# Generated by Django 3.2.15 on 2023-10-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('content_type', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(null=True, upload_to='files/images/%Y/%m')),
                ('uid', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
